/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type T = bigint;
export interface TeamMember {
    ign: string;
}
export interface TournamentFilters {
    region?: string;
    status?: InternalTournamentStatus;
    name?: string;
}
export interface TeamRegistration {
    id: bigint;
    teamName?: string;
    members: Array<TeamMember>;
    createdAt: Time;
    captain: Principal;
    tournamentId: T;
}
export interface UserProfile {
    name: string;
}
export interface PublicTournament {
    id: T;
    region: string;
    startTime: Time;
    status: InternalTournamentStatus;
    organizer: Principal;
    teamSize: bigint;
    entryType: Variant_duo_custom_solo_squad;
    maxSlots: bigint;
    registrationStart: Time;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    prizeDetails: string;
    registrationEnd: Time;
    rules: string;
}
export enum InternalTournamentStatus {
    cancelled = "cancelled",
    started = "started",
    open = "open",
    completed = "completed",
    locked = "locked",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_duo_custom_solo_squad {
    duo = "duo",
    custom = "custom",
    solo = "solo",
    squad = "squad"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelTeamRegistration(registrationId: bigint): Promise<void>;
    createTournament(name: string, description: string, rules: string, region: string, startTime: Time, registrationStart: Time, registrationEnd: Time, maxSlots: bigint, teamSize: bigint, entryType: Variant_duo_custom_solo_squad, prizeDetails: string): Promise<T>;
    getAllTournaments(): Promise<Array<PublicTournament>>;
    getAllTournamentsFiltered(filters: TournamentFilters): Promise<Array<PublicTournament>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getTeamRegistrations(tournamentId: T): Promise<Array<TeamRegistration>>;
    getTournament(id: T): Promise<PublicTournament | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerTeam(tournamentId: T, teamName: string | null, members: Array<TeamMember>): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateTournament(id: T, name: string | null, description: string | null, rules: string | null, region: string | null, startTime: Time | null, registrationStart: Time | null, registrationEnd: Time | null, maxSlots: bigint | null, teamSize: bigint | null, entryType: Variant_duo_custom_solo_squad | null, prizeDetails: string | null): Promise<void>;
    updateTournamentStatus(id: T, status: InternalTournamentStatus): Promise<void>;
}
import type { InternalTournamentStatus as _InternalTournamentStatus, PublicTournament as _PublicTournament, T as _T, TeamMember as _TeamMember, TeamRegistration as _TeamRegistration, Time as _Time, TournamentFilters as _TournamentFilters, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelTeamRegistration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelTeamRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelTeamRegistration(arg0);
            return result;
        }
    }
    async createTournament(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: Time, arg6: Time, arg7: bigint, arg8: bigint, arg9: Variant_duo_custom_solo_squad, arg10: string): Promise<T> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg9), arg10);
            return result;
        }
    }
    async getAllTournaments(): Promise<Array<PublicTournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTournaments();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTournaments();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTournamentsFiltered(arg0: TournamentFilters): Promise<Array<PublicTournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTournamentsFiltered(to_candid_TournamentFilters_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTournamentsFiltered(to_candid_TournamentFilters_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamRegistrations(arg0: T): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamRegistrations(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamRegistrations(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournament(arg0: T): Promise<PublicTournament | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerTeam(arg0: T, arg1: string | null, arg2: Array<TeamMember>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTeam(arg0, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTeam(arg0, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateTournament(arg0: T, arg1: string | null, arg2: string | null, arg3: string | null, arg4: string | null, arg5: Time | null, arg6: Time | null, arg7: Time | null, arg8: bigint | null, arg9: bigint | null, arg10: Variant_duo_custom_solo_squad | null, arg11: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournament(arg0, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournament(arg0, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
    async updateTournamentStatus(arg0: T, arg1: InternalTournamentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentStatus(arg0, to_candid_InternalTournamentStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentStatus(arg0, to_candid_InternalTournamentStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_InternalTournamentStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InternalTournamentStatus): InternalTournamentStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PublicTournament_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicTournament): PublicTournament {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TeamRegistration_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamRegistration): TeamRegistration {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicTournament]): PublicTournament | null {
    return value.length === 0 ? null : from_candid_PublicTournament_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    teamName: [] | [string];
    members: Array<_TeamMember>;
    createdAt: _Time;
    captain: Principal;
    tournamentId: _T;
}): {
    id: bigint;
    teamName?: string;
    members: Array<TeamMember>;
    createdAt: Time;
    captain: Principal;
    tournamentId: T;
} {
    return {
        id: value.id,
        teamName: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.teamName)),
        members: value.members,
        createdAt: value.createdAt,
        captain: value.captain,
        tournamentId: value.tournamentId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _T;
    region: string;
    startTime: _Time;
    status: _InternalTournamentStatus;
    organizer: Principal;
    teamSize: bigint;
    entryType: {
        duo: null;
    } | {
        custom: null;
    } | {
        solo: null;
    } | {
        squad: null;
    };
    maxSlots: bigint;
    registrationStart: _Time;
    name: string;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    prizeDetails: string;
    registrationEnd: _Time;
    rules: string;
}): {
    id: T;
    region: string;
    startTime: Time;
    status: InternalTournamentStatus;
    organizer: Principal;
    teamSize: bigint;
    entryType: Variant_duo_custom_solo_squad;
    maxSlots: bigint;
    registrationStart: Time;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    prizeDetails: string;
    registrationEnd: Time;
    rules: string;
} {
    return {
        id: value.id,
        region: value.region,
        startTime: value.startTime,
        status: from_candid_InternalTournamentStatus_n7(_uploadFile, _downloadFile, value.status),
        organizer: value.organizer,
        teamSize: value.teamSize,
        entryType: from_candid_variant_n9(_uploadFile, _downloadFile, value.entryType),
        maxSlots: value.maxSlots,
        registrationStart: value.registrationStart,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        prizeDetails: value.prizeDetails,
        registrationEnd: value.registrationEnd,
        rules: value.rules
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    started: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    locked: null;
} | {
    draft: null;
}): InternalTournamentStatus {
    return "cancelled" in value ? InternalTournamentStatus.cancelled : "started" in value ? InternalTournamentStatus.started : "open" in value ? InternalTournamentStatus.open : "completed" in value ? InternalTournamentStatus.completed : "locked" in value ? InternalTournamentStatus.locked : "draft" in value ? InternalTournamentStatus.draft : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duo: null;
} | {
    custom: null;
} | {
    solo: null;
} | {
    squad: null;
}): Variant_duo_custom_solo_squad {
    return "duo" in value ? Variant_duo_custom_solo_squad.duo : "custom" in value ? Variant_duo_custom_solo_squad.custom : "solo" in value ? Variant_duo_custom_solo_squad.solo : "squad" in value ? Variant_duo_custom_solo_squad.squad : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamRegistration>): Array<TeamRegistration> {
    return value.map((x)=>from_candid_TeamRegistration_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicTournament>): Array<PublicTournament> {
    return value.map((x)=>from_candid_PublicTournament_n5(_uploadFile, _downloadFile, x));
}
function to_candid_InternalTournamentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InternalTournamentStatus): _InternalTournamentStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentFilters_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentFilters): _TournamentFilters {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_duo_custom_solo_squad | null): [] | [{
        duo: null;
    } | {
        custom: null;
    } | {
        solo: null;
    } | {
        squad: null;
    }] {
    return value === null ? candid_none() : candid_some(to_candid_variant_n3(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region?: string;
    status?: InternalTournamentStatus;
    name?: string;
}): {
    region: [] | [string];
    status: [] | [_InternalTournamentStatus];
    name: [] | [string];
} {
    return {
        region: value.region ? candid_some(value.region) : candid_none(),
        status: value.status ? candid_some(to_candid_InternalTournamentStatus_n12(_uploadFile, _downloadFile, value.status)) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InternalTournamentStatus): {
    cancelled: null;
} | {
    started: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    locked: null;
} | {
    draft: null;
} {
    return value == InternalTournamentStatus.cancelled ? {
        cancelled: null
    } : value == InternalTournamentStatus.started ? {
        started: null
    } : value == InternalTournamentStatus.open ? {
        open: null
    } : value == InternalTournamentStatus.completed ? {
        completed: null
    } : value == InternalTournamentStatus.locked ? {
        locked: null
    } : value == InternalTournamentStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_duo_custom_solo_squad): {
    duo: null;
} | {
    custom: null;
} | {
    solo: null;
} | {
    squad: null;
} {
    return value == Variant_duo_custom_solo_squad.duo ? {
        duo: null
    } : value == Variant_duo_custom_solo_squad.custom ? {
        custom: null
    } : value == Variant_duo_custom_solo_squad.solo ? {
        solo: null
    } : value == Variant_duo_custom_solo_squad.squad ? {
        squad: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
