/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const T = IDL.Nat;
export const InternalTournamentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'started' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'locked' : IDL.Null,
  'draft' : IDL.Null,
});
export const PublicTournament = IDL.Record({
  'id' : T,
  'region' : IDL.Text,
  'startTime' : Time,
  'status' : InternalTournamentStatus,
  'organizer' : IDL.Principal,
  'teamSize' : IDL.Nat,
  'entryType' : IDL.Variant({
    'duo' : IDL.Null,
    'custom' : IDL.Null,
    'solo' : IDL.Null,
    'squad' : IDL.Null,
  }),
  'maxSlots' : IDL.Nat,
  'registrationStart' : Time,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'prizeDetails' : IDL.Text,
  'registrationEnd' : Time,
  'rules' : IDL.Text,
});
export const TournamentFilters = IDL.Record({
  'region' : IDL.Opt(IDL.Text),
  'status' : IDL.Opt(InternalTournamentStatus),
  'name' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TeamMember = IDL.Record({ 'ign' : IDL.Text });
export const TeamRegistration = IDL.Record({
  'id' : IDL.Nat,
  'teamName' : IDL.Opt(IDL.Text),
  'members' : IDL.Vec(TeamMember),
  'createdAt' : Time,
  'captain' : IDL.Principal,
  'tournamentId' : T,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTeamRegistration' : IDL.Func([IDL.Nat], [], []),
  'createTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        Time,
        IDL.Nat,
        IDL.Nat,
        IDL.Variant({
          'duo' : IDL.Null,
          'custom' : IDL.Null,
          'solo' : IDL.Null,
          'squad' : IDL.Null,
        }),
        IDL.Text,
      ],
      [T],
      [],
    ),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(PublicTournament)], ['query']),
  'getAllTournamentsFiltered' : IDL.Func(
      [TournamentFilters],
      [IDL.Vec(PublicTournament)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTeamRegistrations' : IDL.Func(
      [T],
      [IDL.Vec(TeamRegistration)],
      ['query'],
    ),
  'getTournament' : IDL.Func([T], [IDL.Opt(PublicTournament)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerTeam' : IDL.Func(
      [T, IDL.Opt(IDL.Text), IDL.Vec(TeamMember)],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTournament' : IDL.Func(
      [
        T,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(
          IDL.Variant({
            'duo' : IDL.Null,
            'custom' : IDL.Null,
            'solo' : IDL.Null,
            'squad' : IDL.Null,
          })
        ),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateTournamentStatus' : IDL.Func([T, InternalTournamentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const T = IDL.Nat;
  const InternalTournamentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'started' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'locked' : IDL.Null,
    'draft' : IDL.Null,
  });
  const PublicTournament = IDL.Record({
    'id' : T,
    'region' : IDL.Text,
    'startTime' : Time,
    'status' : InternalTournamentStatus,
    'organizer' : IDL.Principal,
    'teamSize' : IDL.Nat,
    'entryType' : IDL.Variant({
      'duo' : IDL.Null,
      'custom' : IDL.Null,
      'solo' : IDL.Null,
      'squad' : IDL.Null,
    }),
    'maxSlots' : IDL.Nat,
    'registrationStart' : Time,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'prizeDetails' : IDL.Text,
    'registrationEnd' : Time,
    'rules' : IDL.Text,
  });
  const TournamentFilters = IDL.Record({
    'region' : IDL.Opt(IDL.Text),
    'status' : IDL.Opt(InternalTournamentStatus),
    'name' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TeamMember = IDL.Record({ 'ign' : IDL.Text });
  const TeamRegistration = IDL.Record({
    'id' : IDL.Nat,
    'teamName' : IDL.Opt(IDL.Text),
    'members' : IDL.Vec(TeamMember),
    'createdAt' : Time,
    'captain' : IDL.Principal,
    'tournamentId' : T,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTeamRegistration' : IDL.Func([IDL.Nat], [], []),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          Time,
          IDL.Nat,
          IDL.Nat,
          IDL.Variant({
            'duo' : IDL.Null,
            'custom' : IDL.Null,
            'solo' : IDL.Null,
            'squad' : IDL.Null,
          }),
          IDL.Text,
        ],
        [T],
        [],
      ),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(PublicTournament)], ['query']),
    'getAllTournamentsFiltered' : IDL.Func(
        [TournamentFilters],
        [IDL.Vec(PublicTournament)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTeamRegistrations' : IDL.Func(
        [T],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'getTournament' : IDL.Func([T], [IDL.Opt(PublicTournament)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerTeam' : IDL.Func(
        [T, IDL.Opt(IDL.Text), IDL.Vec(TeamMember)],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTournament' : IDL.Func(
        [
          T,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(
            IDL.Variant({
              'duo' : IDL.Null,
              'custom' : IDL.Null,
              'solo' : IDL.Null,
              'squad' : IDL.Null,
            })
          ),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateTournamentStatus' : IDL.Func([T, InternalTournamentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };