/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type InternalTournamentStatus = { 'cancelled' : null } |
  { 'started' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'locked' : null } |
  { 'draft' : null };
export interface PublicTournament {
  'id' : T,
  'region' : string,
  'startTime' : Time,
  'status' : InternalTournamentStatus,
  'organizer' : Principal,
  'teamSize' : bigint,
  'entryType' : { 'duo' : null } |
    { 'custom' : null } |
    { 'solo' : null } |
    { 'squad' : null },
  'maxSlots' : bigint,
  'registrationStart' : Time,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'prizeDetails' : string,
  'registrationEnd' : Time,
  'rules' : string,
}
export type T = bigint;
export interface TeamMember { 'ign' : string }
export interface TeamRegistration {
  'id' : bigint,
  'teamName' : [] | [string],
  'members' : Array<TeamMember>,
  'createdAt' : Time,
  'captain' : Principal,
  'tournamentId' : T,
}
export type Time = bigint;
export interface TournamentFilters {
  'region' : [] | [string],
  'status' : [] | [InternalTournamentStatus],
  'name' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTeamRegistration' : ActorMethod<[bigint], undefined>,
  'createTournament' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Time,
      Time,
      Time,
      bigint,
      bigint,
      { 'duo' : null } |
        { 'custom' : null } |
        { 'solo' : null } |
        { 'squad' : null },
      string,
    ],
    T
  >,
  'getAllTournaments' : ActorMethod<[], Array<PublicTournament>>,
  'getAllTournamentsFiltered' : ActorMethod<
    [TournamentFilters],
    Array<PublicTournament>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTeamRegistrations' : ActorMethod<[T], Array<TeamRegistration>>,
  'getTournament' : ActorMethod<[T], [] | [PublicTournament]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerTeam' : ActorMethod<[T, [] | [string], Array<TeamMember>], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTournament' : ActorMethod<
    [
      T,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [Time],
      [] | [Time],
      [] | [Time],
      [] | [bigint],
      [] | [bigint],
      [] | [
        { 'duo' : null } |
          { 'custom' : null } |
          { 'solo' : null } |
          { 'squad' : null }
      ],
      [] | [string],
    ],
    undefined
  >,
  'updateTournamentStatus' : ActorMethod<
    [T, InternalTournamentStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];